spring:
  datasource:
    username: cloudbi
    password: cloudbi
    url: jdbc:postgresql://192.168.4.30:5432/druiddemo
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
#    type: com.alibaba.druid.pool.DruidDataSource

#    initialSize: 5